### ISSUE TITLE
Getting a list of resources fails, if not logged in

### ISSUE THREAD

**Issue by avodovnik** [bradygaster/azure-tools-vscode#10]
If you're not logged in, and you click on an operation, e.g. "Browse in portal", it perpetually stays in "Getting your list of resources". I would expect all operations that rely on the token being present, to make sure it's valid at start. 

![image](https://cloud.githubusercontent.com/assets/1932563/19908227/32b36282-a07a-11e6-9a1d-8269bd01b8af.png)

Note, I'm probably going to implement a _service-wide_ check for this, with the refactor.

**Comment by avodovnik** [comment]
![image](https://cloud.githubusercontent.com/assets/1932563/20115275/96876cca-a5ef-11e6-9589-eb5295e32a53.png)

It's in my branch, for now, but I'll check it all in fairly shortly hopefully.

**Comment by cmatskas** [comment]
@bradygaster should we not have a global `try...catch` for all Azure commands to let users know that they need to log in first?

**Comment by bradygaster** [comment]
@cmatskas absolutely.

**Comment by bradygaster** [comment]
@avodovnik and @cmatskas just resolved this one. would love to have your sign-off

**Comment by cmatskas** [comment]
@bradygaster which branch do I need to grab to test this? did you merge to master already?
