### ISSUE TITLE
Update is not available in code UI

### ISSUE THREAD

**Issue by SteveALee** [bradygaster/azure-tools-vscode#12]
I have 0.0.5 installed as show in the installed extension list  but I see 0.0.9 is in the market place. however Unlike other extensions I do not get an upgrade offer in the list. Looks like I need to uninstall and re-install.

It seems to be within semver critieria.

**Comment by bradygaster** [comment]
@SteveALee the reason for this is that we needed to change the publisher at 0.0.5 - long story. Uninstall the one you have, then restart @code and do another search for "Azure Tools" in the extensions search box. You'll see it's listed under my account name, not Microsoft's. We'll get there, I hope. :)
