### ISSUE TITLE
Add support for KeyVault

### ISSUE THREAD

**Issue by cmatskas** [bradygaster/azure-tools-vscode#16]
This is a feature request and one that I would personally like to take on. Happy to fork and send a PR for now instead of joining the contributors list (at this point anyway)

Azure Key Vault is fully supported in the .NET SDK and I've done quite a bit of work with it so keen to extend my knowledge and help make this VS Code extension better :)

**Comment by bradygaster** [comment]
Merged! Thanks for the contribution, @cmatskas! This is rad.
