### ISSUE TITLE
Escaping a Web app Creation isn't handled properly

### ISSUE THREAD

**Issue by avodovnik** [bradygaster/azure-tools-vscode#2]
Steps to reproduce:

1. Start creation of a new Web App (Advanced)
2. Instead of entering a name, leave it empty and press ESC

Expected:

1. Nothing should happen, the dialog should close.

Actual:

1. An Error message appears that says "The Web App Name is not available."

![image](https://cloud.githubusercontent.com/assets/1932563/19760912/ae3bee5e-9c2b-11e6-802b-4b1582b962e2.png)

**Comment by bradygaster** [comment]
@avodovnik this is a good catch. i like it. this shall happen

**Comment by avodovnik** [comment]
So, I've had a quick look, and got the fix in. Submitting a pull request now. Let me know if you're happy with it, and I'm happy to work on it further (can do with some improving).

**Comment by avodovnik** [comment]
Looks like the way I fixed the issue is incorrect - which is why you had to fix the fix. I've done more research and it turns out the fix to fix the fix also needs fixing, so I fixed it. I'll submit a PR soon.

See here: https://github.com/Microsoft/vscode/issues/11503
