### ISSUE TITLE
ARM Template JSON Outliner

### ISSUE THREAD

**Issue by tripdubroot** [bradygaster/azure-tools-vscode#31]
Provide a generic outline of the resources in ARM templates.

**Comment by bradygaster** [comment]
@tripdubroot what do you mean exactly? i think that might be something the ARM editor tool can do (or should do) but i want to understand your idea better. could you elaborate?

**Comment by bradygaster** [comment]
marking this as won't fix. would recommend you take a look at the [ARM Tools](https://marketplace.visualstudio.com/items?itemName=msazurermtools.azurerm-vscode-tools), which this project depends upon. It provides good outliner capabilities, as well as IntelliSense features and snippets.
