### ISSUE TITLE
Is there a way to debug ARM deployment failures?

### ISSUE THREAD

**Issue by dawilliams** [bradygaster/azure-tools-vscode#33]
I don't see a way to debug ARM deployment failures.  It just says that it failed.  Also it is telling me that it failed when it hasn't after creating a resource group

**Comment by bradygaster** [comment]
@dawilliams this is a great piece of feedback - i'm not quite sure the scope of this feature but will do some investigating and keep this issue up to date as we determine how/if we can do this in the extension. thanks for the feedback, this is a great idea.

**Comment by dawilliams** [comment]
@bradygaster Thanks!  I love VSCode and the potential this extension has.  Currently I use the ISE but that forces me to log into Azure for every test iteration that I run.  I was hoping that in addition to using VSCode , this extension would not force me to log in every time.  Thanks again!

**Comment by cmatskas** [comment]
@dawilliams with the extension, once you log in, you're in. Unless you close down VS Code, the extension will work as expected. Please note that you can also use PoSH or the default command-line tool inside VS Code if you want to alternate between the 2

**Comment by avodovnik** [comment]
On the login issue - that's actually something I was looking into, and it's a bit of a nightmare to try and store that login securely. I've got a long-running conversation thread open with @bradygaster and some of the team members around this, so maybe it'll happen. But it's not easy or quick.

**Comment by bradygaster** [comment]
in the 1.2.3 release we're logging much more diagnostics information to the VS Code output window. Take a look there when you do something that fails or takes a long time, and if you see errors or issues reported there or see API conversations that don't make sense feel free to copy/paste what you see in the output window and create another issue. Thanks!
