### ISSUE TITLE
For deployment, use open folder instead of 'arm-templates'

### ISSUE THREAD

**Issue by jefutte** [bradygaster/azure-tools-vscode#34]
Not everyone has their templates in a folder named 'arm-templates'. Would be great if we could use the root of the folder we have open instead. Nice extension though!

**Comment by bradygaster** [comment]
@jefutte that's a good suggestion but one that i'm somewhat hesitant about making at the moment. i contemplate putting the templates into the .vscode folder so they're more editor resources than project resources. How about that?

**Comment by benc-uk** [comment]
I think putting them .vscode is a mistake, a lot of people put that folder in their .gitignore and treat it as not part of their project
What about having a option in settings.json? Define the template folder there, either '.' for the root of the project or 'arm-templates' (or whatever other folder people might want)

**Comment by bradygaster** [comment]
after some consideration i'm going to close this as by-design for now. if there's more merit to it or a PR i'll take it for consideration.
