### ISSUE TITLE
Deploying a template results in a error.

### ISSUE THREAD

**Issue by rdtechie** [bradygaster/azure-tools-vscode#37]
I'm trying to deploy just a plain template from the quickstart gallery, but it doesn't work. I'm trying this on a vanilla installation of Windows 10 1607 with either Visual Studio 1.9 or Visual Studio Code insiders.
![2017-02-16_21-55-30](https://cloud.githubusercontent.com/assets/6579452/23040763/d3fb01ba-f492-11e6-9635-d745d5f48b81.gif)

**Comment by bradygaster** [comment]
@rdtechie sorry for the delay, been busy with regular work and other projects. Could you let me know which template you're using from the gallery? Apologies for a silly question but your video/animgif is REALLY small and I can't see which template you're grabbing or how you're customizing it. 

Thanks!

**Comment by bradygaster** [comment]
I've updated the extension in 1.2.3 to provide more information and a debug log in the output window. This should give you more insight into what's happening when you reach out to the API. If you continue to experience issues with this feature please copy-paste any output log you see relevant to it and give me a new issue and I'll investigate. Thanks so much!
