### ISSUE TITLE
Performing Azure: Login multiple times duplicates subscriptions in subs list. 

### ISSUE THREAD

**Issue by oising** [bradygaster/azure-tools-vscode#39]
Steps to Reproduce:

1. Invoke Azure: Login
2. Authenticate
3. Invoke Azure: List Subs (shows my three subs)
4. Invoke Azure: Login
5. Authenticate
6. Invoke Azure: List Subs (shows six subs - my three subs each showing twice)

**Comment by bradygaster** [comment]
resolved with #51
