### ISSUE TITLE
When a subscription is selected, the tooltip isn't updated

### ISSUE THREAD

**Issue by avodovnik** [bradygaster/azure-tools-vscode#4]
Unlike the Region selection, when you select a subscription, the button's tooltip isn't updated to reflect the choice.

**Comment by bradygaster** [comment]
this would be a good thing to get in there. at the same time it'd be good to add functionality so that we tell the user in the tooltip for the region selection which region is selected at first login

**Comment by avodovnik** [comment]
So, the refactor I'm working on should technically have this in. I looked at the code, and it's not as easy at the moment, as the calls are in two distinct locations. I'll have a play with this.

**Comment by bradygaster** [comment]
@avodovnik this has been resolved in the next release
