### ISSUE TITLE
Errors are note taced out

### ISSUE THREAD

**Issue by jkristia** [bradygaster/azure-tools-vscode#40]
This is probably an enhancement request.

I just installed the extension and was trying to create a function app. Login and selecting subscription seemed to work, but it seemed hung when creating the app.
I checked in the console, and the 401 error returned from Azure is not traced out, instead it just appeared hung.
Now - my problem turned out that I forgot to add the tenantId to the settings. Once I did that and logged in again, it worked.
I think it might be good to have some feedback in the output window when things goes wrong.

![notenanttoken](https://cloud.githubusercontent.com/assets/3513311/25072498/7cbee144-2284-11e7-9c25-257971bbb64d.jpg)

**Comment by bradygaster** [comment]
This has been resolved in the 1.2.3 update. Update your extension and you'll see more details surfaced in the output window when things happen. 

Then you can use this information as a copy/paste into a new GitHub issue and I'll have the details of your issue and would be better equipped to help out. 

Thanks!
