### ISSUE TITLE
Last chosen subscription & region should be remembered

### ISSUE THREAD

**Issue by avodovnik** [bradygaster/azure-tools-vscode#6]
It'd be useful, if I sign in with the same username & password (we need to open a separate issue to keep the tokens longer, if possible?), the selection of the subscription and region (potentially) is remembered.

**Comment by bradygaster** [comment]
after much thought on this i don't think the extension needs to be given this functionality yet. this is a higher-level feature that'd serve *any* extension, so i don't want to pre-empt any work that might be done here. if there was a centralized AAD client within code that would be awesome. Closing for now.
