### ISSUE TITLE
Selecting the Azure Subscription fails for multiple subscriptions with equal name

### ISSUE THREAD

**Issue by avodovnik** [bradygaster/azure-tools-vscode#7]
I have multiple subscriptions that (for whatever strange reason - namely laziness of their owners) share the same name. When switching subscriptions, it is hard to distinguish between them, and selecting the "second one" doesn't work.

- Add an ID to the list, so that you can make an educated guess
- Change the filter logic of the subscription to include the id as well as the name

**Comment by avodovnik** [comment]
Separated this out into name + id for the quick list item.

![image](https://cloud.githubusercontent.com/assets/1932563/20115357/ee0aef12-a5ef-11e6-988f-046b0feca388.png)

**Comment by bradygaster** [comment]
@avodovnik resolved
